apiVersion: v1
kind: ConfigMap
metadata:
  name: application-config
  namespace: shopbia
#common configuration shared between all applications
data:
  application.yml: |-
    configserver:
      name:  JHipster Registry
      status: Connected to the JHipster Registry running in Kubernetes
    eureka:
      client:
        initial-instance-info-replication-interval-seconds: 500
        instance-info-replication-interval-seconds: 500
        registry-fetch-interval-seconds: 500
        fetch-registry: true
        register-with-eureka: true
        eureka-service-url-poll-interval-seconds: 500
        service-url:
          defaultZone: http://admin:${spring.security.user.password}@jhipster-registry-0.jhipster-registry.shopbia.svc.cluster.local:8761/eureka
      instance:
        lease-renewal-interval-in-seconds: 500
        registry-default-open-for-traffic-count: 0
    jhipster:
      security:
        authentication:
          jwt:
            base64-secret: OTQ3ZTZmZGNmZTU1MWViMzZlY2M1M2I1OTUwY2Y5YjRmMzU3ZDlmNTkxNDkzMDQ2ODkwZDgwNWY0OWYwNzhmZWM1NjhiOTM0ODY0ZTQ2YzNlODFkN2E2NmFiZWZmMTE0NDIyNw==
  
  #app specific configuration
  jhipster-registry.yml: |-
    eureka:
      client:
        service-url:
          defaultZone: http://admin:${spring.security.user.password}@jhipster-registry-0.jhipster-registry.shopbia.svc.cluster.local:8761/eureka