apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-gateway
  namespace: abed-roost
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-gateway
  namespace: abed-roost
  labels:
    app: gateway-pvc
spec:
  storageClassName: manual
  volumeName: pv-gateway
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi