apiVersion: apps/v1
kind: Deployment
metadata:
  name:  user-deployment
  namespace: abed-roost
  labels:
    app:  user-deployment
spec:
  selector:
    matchLabels:
      app: user-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app:  user-deployment
    spec:
      containers:
      - name:  user-deployment
        image:  abdalrhmanalkraien/user-service:latest
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: user-config
              key: profile
        - name: MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED
          value: "false"
        - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
          value: http://admin:$${jhipster.registry.password}@jhipster-registry.abed-roost.svc.cluster.local:8761/eureka
        - name: SPRING_CLOUD_CONFIG_URI
          value: http://admin:$${jhipster.registry.password}@jhipster-registry.abed-roost.svc.cluster.local:8761/config
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql-service:3306/food_db?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
        - name: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI
          value: http://13.235.13.30.nip.io/auth/realms/jhipster
        - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_ID
          value: web_app
        - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_SECRET
          value: web_app
        - name: KEYCLOAK_REALM
          value: jhipster
        - name: KEYCLOAK_SERVER_URL
          value: http://keycloack-service:9080/auth
        - name: KEYCLOAK_ADMIN_CLIENT_ID
          value: admin-cli
        - name: KEYCLOAK_USERNAME
          value: admin
        - name: KEYCLOAK_PASSWORD
          value: admin
        - name: KAFKA_BOOTSTRAPSERVERS 
          value: kafka-service:9092
        ports:
        - containerPort:  8084
          name:  user
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: abed-roost
spec:
  selector:
    app: user-deployment
  ports:
  - name: user-service
    protocol: TCP
    port: 8084
    targetPort: 8084
