apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-key
  namespace: shopbia
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: key-pvc
  namespace: shopbia
  labels:
    app: key-pvc
spec:
  storageClassName: manual
  volumeName: pv-key
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi