
apiVersion: v1
kind: Service
metadata:
  name: jhipster-registry
  namespace: abed-roost
  labels:
    app: jhipster-registry
spec:
  selector:
    app: jhipster-registry
  type: LoadBalancer 
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
      nodePort: 30011
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jhipster-registry
  namespace: abed-roost
  labels: 
    app: jhipster-registry
spec:
  # added to circumvent kustomize bug
  volumeClaimTemplates: []
  serviceName: jhipster-registry
  replicas: 2
  selector:
    matchLabels:
      app: jhipster-registry
      version: "1.0"
  template:
    metadata:
      labels:
        app: jhipster-registry
        version: "1.0"
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: jhipster-registry
        image: jhipster/jhipster-registry:v6.3.0
        ports:
          - containerPort: 8761
        env:
        - name: _JAVA_OPTIONS
          valueFrom:
            configMapKeyRef:
              name: registry-config
              key: java-opt

        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: registry-config
              key: profile


        - name: SPRING_SECURITY_USER_PASSWORD
          value: admin
          # valueFrom:
          #   secretKeyRef:
          #     name: registry-secret
          #     key: spring_security_user_password



        - name: JHIPSTER_REGISTRY_PASSWORD
          value: admin
          # valueFrom:
          #   secretKeyRef:
          #     name: registry-secret
          #     key: registry_password
        
        - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
          value: "false"

        - name: SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_TYPE
          value: native

        - name: SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_SEARCH_LOCATIONS
          value: file:./central-config
        - name: EUREKA_INSTANCE_LEASE_RENEWAL_INTERVAL_IN_SECONDS
          value: "15"
        - name: EUREKA_INSTANCE_LEASE_EXPIRATION_DURATION_IN_SECONDS
          value: "30"
        - name: EUREKA_SERVER_PEER_EUREKA_NODES_UPDATE_INTERVAL_MS
          value: "15000"
        - name: EUREKA_SERVER_RENAWAL_THRESHOLD_UPDATE_INTERVAL_MS
          value: "15000"
        - name: EUREKA_SERVER_REGISTRY_SYNC_RETRIES
          value: "3"
        - name: EUREKA_SERVER_ENABLE_SELF_PRESERVATION
          value: "false"
        - name: EUREKA_SERVER_PEER_NODE_CONNECT_TIMEOUT_MS
          value: "2000"
        - name: EUREKA_CLIENT_FETCH_REGISTRY
          value: "true"
        - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
          value: "true"

        - name: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI
          #value: http://shop.com/auth/realms/jhipster
          value: http://13.235.13.30.nip.io/auth/realms/jhipster

        - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_ID
          value: jhipster-registry

        - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_SECRET
          value: jhipster-registry
        # - name: K8S_CONFIG_PATH
        #   value: "/central-config/"
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: EUREKA_INSTANCE_HOSTNAME
          value: ${MY_POD_NAME}.eureka
        # command:
        #   - "/bin/sh"
        #   - "-ec"
        #   - |
        #     echo "my pod name  ${MY_POD_NAME}"
        #    HOSTNAME=$(hostname)
        #     export EUREKA_INSTANCE_HOSTNAME="${HOSTNAME}.jhipster-registry.${DEPLOYMENT_NAMESPACE}.svc.cluster.local"
        #     echo "Setting EUREKA_INSTANCE_HOSTNAME=${EUREKA_INSTANCE_HOSTNAME}"
        #     echo "Configuring Registry Replicas for CLUSTER_SIZE=${CLUSTER_SIZE}"
        #     echo "my host name  ${HOSTNAME}"
        #     LAST_POD_INDEX=$((${CLUSTER_SIZE} - 1))
        #     REPLICAS=""
        #     for i in $(seq 0 $LAST_POD_INDEX); do
        #       REPLICAS="${REPLICAS}http://admin:${SECURITY_USER_PASSWORD}@${DEPLOYMENT_NAME}-${i}.jhipster-registry.${DEPLOYMENT_NAME}.svc.cluster.local:8761/eureka/"
        #       if [ $i -lt $LAST_POD_INDEX ]; then
        #         REPLICAS="${REPLICAS},"
        #       fi
        #     done
        #     export EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=$REPLICAS
        #     echo "EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=${REPLICAS}"
        #     java -jar /jhipster-registry.war --spring.cloud.config.server.git.uri=${GIT_URI} --spring.cloud.config.server.git.search-paths=${GIT_SEARCH_PATHS} -Djava.security.egd=file:/dev/./urandom
          
        volumeMounts:
        - name: central-config
          mountPath: /central-config
      volumes:
        - name: central-config
          configMap:
            name: application-config
