apiVersion: v1
kind: Service
metadata:
  name: jhipster-registry
  namespace: shopbia
  labels:
    app: jhipster-registry
spec:
  selector:
    app: jhipster-registry
  type: LoadBalancer 
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
      nodePort: 30011