apiVersion: apps/v1
kind: Deployment
metadata:
  name:  kafka-deployment
  namespace: shopbia
  labels:
    app:  kafka-deployment
spec:
  selector:
    matchLabels:
      app: kafka-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka-deployment
    spec:
      containers:
      - name: kafka-deployment
        image:  confluentinc/cp-kafka:5.5.0
        env:
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: 192.168.99.113
        - name: LISTENERS
          value: PLAINTEXT://:9092
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://kafka:9092

        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper-service:2181
        
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
        
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: PLAINTEXT         
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"                                       
        ports:
        - containerPort:  9092
          name:  kafka-port
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: shopbia
  labels:
    app: kafka
spec:
  selector:
    app: kafka-deployment
  type: ClusterIP
  ports:
  - name: kafka
    protocol: TCP
    port: 9092
    targetPort: 9092