apiVersion: apps/v1
kind: Deployment
metadata:
  name:  zookeeper-deployment
  namespace: shopbia
  labels:
    app:  zookeeper-deployment
spec:
  selector:
    matchLabels:
      app: zookeeper-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app:  zookeeper-deployment
    spec:
      containers:
      - name:  zookeeper-deployment
        image:  confluentinc/cp-zookeeper:5.5.0
        env:
        - name: ZOOKEEPER_CLIENT_PORT
          value: "2181"
        - name: ZOOKEEPER_TICK_TIME
          value: "2000"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
  namespace: shopbia
spec:
  selector:
    app: zookeeper-deployment
  type: ClusterIP
  ports:
  - name: zookeeper-service
    protocol: TCP
    port: 2181
    targetPort: 2181